### ISSUE TITLE
Display Error on Recipe Description Load Failure

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#12]
### SCENARIO: 
  
  - Display error message when recipe description fails to load
    
    ### GIVEN: 
    
    - I am viewing the list of recipe previews
    
    ### WHEN: 
    
    - I navigate to a specific recipe page
    - **AND** the recipe description fails to load due to a network error
    
    ### THEN: 
    
    - I should see an error message stating 'Failed to load description'

**Comment by OnalennaRammapatsi** [comment]
Displayed an error message when a recipe description fails to load.

**Comment by Renzo-codespace** [comment]
The solution to this issue must be demonstrated before it can be considered as done.

**Comment by Renzo-codespace** [comment]
I think I may need glasses, but this is done!!!

**Comment by ElzabeEls** [comment]
Renzo said: Do not remove line breaks

**Comment by OnalennaRammapatsi** [comment]
> Renzo said: Do not remove line breaks
I don't understand, please clarify a bit more.

**Comment by ElzabeEls** [comment]
@Renzo-codespace Please help

**Comment by Renzo-codespace** [comment]
@ElzabeEls Could you please be more specific about the line breaks you are referring to? I'm not sure what the problem could be if I commented that this is done.

**Comment by ElzabeEls** [comment]
@Renzo-codespace I just copied this over from the notes I took during the demo that we had... I just wanted to see if it sparked any recollection as to how something could possibly be optimised even further or something like that... If its not sparking anything then I probably made the note in the wrong place which means we can move on. Just wanted to be 200% sure 👍🏼 Thank you 🙏🏼
