### ISSUE TITLE
History of previous searches

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#182]
### Scenario: 
  
  - User performs a text search and wants to see the history of previous searches
    
    ### Given: 
    
    - I am a user performing a text search for recipes in the app
    
    ### When: 
    
    - I click on the search box
    
    ### Then: 
    
    - I should see a list of my previous searches

**Comment by Renzo-codespace** [comment]
The solution to this issue must be demonstrated before it can be considered as done.

**Comment by Renzo-codespace** [comment]
Empty strings should not be persisted to the database / search history.

**Comment by ElzabeEls** [comment]
Do not persist empty strings to the database
