### ISSUE TITLE
Debounce auto submission (Long query)

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#185]
### Scenario: 
  
  - User types a long query into the search box
    
    ### Given: 
    
    - I am a user on the search page of the recipe app
    
    ### When: 
    
    - I type a long query into the search box
    - **AND** I pause for a moment while typing
    
    ### Then: 
    
    - The app should not automatically submit the search during my pauses

**Comment by Renzo-codespace** [comment]
The solution to this issue must be demonstrated before it can be considered as done.

**Comment by Renzo-codespace** [comment]
Users should be able to navigate to the search feature.

**Comment by ElzabeEls** [comment]
@Renzo-codespace. Please help me understand what 'Users should be able to navigate to the search feature.' means? Thank you!
