### ISSUE TITLE
Selecting a category filter

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#189]
### Scenario: 
  
  - User can select a category to filter recipes
    
    ### Given: 
    
    - I am on the recipes list page
    
    ### When: 
    
    - I select a specific category from the category filter
    
    ### Then: 
    
    - The filter should be applied to the recipes list

**Comment by Renzo-codespace** [comment]
Currently, searching by category only works if enter a string that exactly matches a category.
This provides little guidance to the user.
A select component or auto-completing component would be more engaging to the user.

**Comment by GirlKat17** [comment]
We currently have two options a select component and a search. so I can delete the search but wouldn't be able to fulfill Issue 191,for no match Categories.
