### ISSUE TITLE
Clearing all selected tags

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#198]
### Scenario: 
  
  - Clear all selected tags
    
    ### Given: 
    
    - I have previously selected multiple tags for filtering recipes
    
    ### When: 
    
    - I choose to clear all selected tags
    
    ### Then: 
    
    - No tags should be selected 
    - **AND** I should see the original, unfiltered list of recipes

**Comment by ElzabeEls** [comment]
Still the case:
'Sort by' did not reset to default.
Asc/Desc also did not reset to Ascending

Also:
Includes button does not result to 'Includes All Ingredients'
