### ISSUE TITLE
User removes all applied filters and views the list of recipes

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#208]
### Scenario: 
  
  - User removes all applied filters and views the list of recipes
    
    ### Given: 
    
    - I am viewing the list of recipes in the app
    - **AND** I have previously applied some filters to my recipe search
    
    ### When: 
    
    - I remove all applied filters
    
    ### Then:
    
    - I should see a message indicating no filters have been applied in the filter indication area

**Comment by ElzabeEls** [comment]
Not when I have previously searched. The message only showed once before I added and then removed filters

**Comment by ElzabeEls** [comment]
In the recipe stats area (where the amount of results are shown etc) there should be a message stating 'No filters applied' when no filters have been applied.

**Comment by ElzabeEls** [comment]
@NeoDitjoe Test properly before merging please:


![Image](https://github.com/CodeSpace-Academy/ASE_2023_GROUP_E/assets/53035581/dad3cd2e-c2ef-4e74-9f57-719994af22f3)


Also... This is in the wrong place. It shouldn't be on the overlay.
