### ISSUE TITLE
Load More button disappearance

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#22]
### SCENARIO: 
  
  - "Load More" button should disappear after all recipes are loaded
    
    ### GIVEN: 
    
    - I am on the recipes list page
    - **AND** I have clicked the "Load More" button until all recipes are loaded
    
    ### WHEN: 
    
    - No more recipes are available
    
    ### THEN: 
    
    - The "Load More" button should disappear

**Comment by Paskay18** [comment]
Load more button disappears when the last recipes are loaded

**Comment by Renzo-codespace** [comment]
The solution to this issue must be demonstrated before it can be considered as done.

**Comment by Renzo-codespace** [comment]
Is good job!
