### ISSUE TITLE
Loading more recipes

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_E#23]
### SCENARIO: 
  
  - User can load more recipes using the "Load More" button
    
    ### GIVEN: 
    
    - I am on the recipes list page
    - **AND** there are more recipes available beyond the current page
    
    ### WHEN: 
    
    - I click on the "Load More" button
    
    ### THEN: 
    
    - Additional recipes should be loaded and appended to the current list

**Comment by Paskay18** [comment]
More recipes can be loaded a 100 at a time using the load more button
