### ISSUE TITLE
Implement Interactive Navigation Closed Icon 

### ISSUE THREAD

**Issue by ElzabeEls** [CodeSpace-Academy/ASE_2023_GROUP_E#312]
### Scenario: 
  
  - Navigation bar icon changes according to if the navigation bar is closed
    
    ### Given: 
    
    - I am anywhere on the site
    
    ### When: 
    
    - The navigation bar is open and i click on the navigation bar icon
    
    ### Then: 
    
    - The navigation bar icon changes to an icon that intuitively indicates that the navigation bar is now closed

**Comment by MichelleMathuloe** [comment]
nav bar is interactive
