### ISSUE TITLE
## Implementing an arrow icon on navigation bar

### ISSUE THREAD

**Issue by ElzabeEls** [CodeSpace-Academy/ASE_2023_GROUP_E#345]
### Scenario: 
  
  - Have an arrow icon that points right when navigation bar is closed
    
    ### Given: 
    
    - I am on deskop view 
    
    ### When: 
    
    - The navigation bar is closed 
    
    ### Then: 
    
    - I should see an arrow icon that points right

**Comment by MichelleMathuloe** [comment]
linked to issue 311
