### ISSUE TITLE
Remove on-hover effect of tag labels

### ISSUE THREAD

**Issue by ElzabeEls** [CodeSpace-Academy/ASE_2023_GROUP_E#373]
### Scenario: 
  
  - Tag labels on search/all recipes page have no interactive effects
    
    ### Given: 
    
    - I am on the search/all recipes page
    
    ### When: 
    
    - I hover over the tag labels
    
    ### Then: 
    
    - Nothing happens
    
<img width="278" alt="image" src="https://github.com/CodeSpace-Academy/ASE_2023_GROUP_E/assets/53035581/0d04c011-c551-4991-b380-58415785399d">

**Comment by Kelello-7206** [comment]
Tirelo already fixed this issue
